{
  "uid" : "de039bb03c3c923a",
  "name" : "Get list of tags",
  "fullName" : "tests.test_tags_controller.TestTags#test_list_tags",
  "historyId" : "40fc6a6db1c1ce9366ccf0698b202bf9",
  "time" : {
    "start" : 1710016702548,
    "stop" : 1710016703203,
    "duration" : 655
  },
  "status" : "broken",
  "statusMessage" : "pydantic_core._pydantic_core.ValidationError: 1 validation error for DataListTags\ndata.0\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.6/v/string_type",
  "statusTrace" : "self = <test_tags_controller.TestTags object at 0x7fe8b99c8da0>\nauthorization = {'app-id': '65d388b26d41f39919c944af'}\n\n    @allure.title('Get list of tags')\n    def test_list_tags(self, authorization):\n        self.list_tags.request_tags_list(authorization)\n        self.list_tags.check_response_is_200()\n>       self.list_tags.check_validate()\n\ntests/test_tags_controller.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <endpoints.tag_controller.list_tags.TagsList object at 0x7fe8b99dfda0>\n\n    @allure.step('Check validate schema')\n    def check_validate(self):\n>       parsed_object = self.SCHEMA.model_validate(self.response_json)\nE       pydantic_core._pydantic_core.ValidationError: 1 validation error for DataListTags\nE       data.0\nE         Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\nE           For further information visit https://errors.pydantic.dev/2.6/v/string_type\n\nbase/base_api.py:12: ValidationError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1710016675739,
      "stop" : 1710016675760,
      "duration" : 21
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "authorization",
    "time" : {
      "start" : 1710016702547,
      "stop" : 1710016702547,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "setup",
    "time" : {
      "start" : 1710016702547,
      "stop" : 1710016702548,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "pydantic_core._pydantic_core.ValidationError: 1 validation error for DataListTags\ndata.0\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.6/v/string_type",
    "statusTrace" : "self = <test_tags_controller.TestTags object at 0x7fe8b99c8da0>\nauthorization = {'app-id': '65d388b26d41f39919c944af'}\n\n    @allure.title('Get list of tags')\n    def test_list_tags(self, authorization):\n        self.list_tags.request_tags_list(authorization)\n        self.list_tags.check_response_is_200()\n>       self.list_tags.check_validate()\n\ntests/test_tags_controller.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <endpoints.tag_controller.list_tags.TagsList object at 0x7fe8b99dfda0>\n\n    @allure.step('Check validate schema')\n    def check_validate(self):\n>       parsed_object = self.SCHEMA.model_validate(self.response_json)\nE       pydantic_core._pydantic_core.ValidationError: 1 validation error for DataListTags\nE       data.0\nE         Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\nE           For further information visit https://errors.pydantic.dev/2.6/v/string_type\n\nbase/base_api.py:12: ValidationError",
    "steps" : [ {
      "name" : "Get tag list",
      "time" : {
        "start" : 1710016702548,
        "stop" : 1710016703202,
        "duration" : 654
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "headers",
        "value" : "{'app-id': '65d388b26d41f39919c944af'}"
      } ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : true
    }, {
      "name" : "Check response is 200",
      "time" : {
        "start" : 1710016703202,
        "stop" : 1710016703202,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "Check validate schema",
      "time" : {
        "start" : 1710016703202,
        "stop" : 1710016703202,
        "duration" : 0
      },
      "status" : "broken",
      "statusMessage" : "pydantic_core._pydantic_core.ValidationError: 1 validation error for DataListTags\ndata.0\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.6/v/string_type\n",
      "statusTrace" : "  File \"/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/usr/workspace/base/base_api.py\", line 12, in check_validate\n    parsed_object = self.SCHEMA.model_validate(self.response_json)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pydantic/main.py\", line 509, in model_validate\n    return cls.__pydantic_validator__.validate_python(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "stepsCount" : 0,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 3,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Tag controller"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_tags_controller"
  }, {
    "name" : "subSuite",
    "value" : "TestTags"
  }, {
    "name" : "host",
    "value" : "cbe4cb7888fc"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_tags_controller"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 5,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 5
      },
      "items" : [ {
        "uid" : "1c8fabb9a3d4faa7",
        "status" : "broken",
        "statusDetails" : "pydantic_core._pydantic_core.ValidationError: 1 validation error for DataListTags\ndata.0\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.6/v/string_type",
        "time" : {
          "start" : 1710001549344,
          "stop" : 1710001550205,
          "duration" : 861
        }
      }, {
        "uid" : "34137adf21aace7c",
        "status" : "broken",
        "statusDetails" : "pydantic_core._pydantic_core.ValidationError: 1 validation error for DataListTags\ndata.0\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.6/v/string_type",
        "time" : {
          "start" : 1709739761238,
          "stop" : 1709739761612,
          "duration" : 374
        }
      }, {
        "uid" : "ed4a63492be128c6",
        "status" : "broken",
        "statusDetails" : "pydantic_core._pydantic_core.ValidationError: 1 validation error for DataListTags\ndata.0\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.6/v/string_type",
        "time" : {
          "start" : 1709561728572,
          "stop" : 1709561729366,
          "duration" : 794
        }
      }, {
        "uid" : "731a6778ae08088c",
        "status" : "broken",
        "statusDetails" : "pydantic_core._pydantic_core.ValidationError: 1 validation error for DataListTags\ndata.0\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.6/v/string_type",
        "time" : {
          "start" : 1709561495752,
          "stop" : 1709561496277,
          "duration" : 525
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "de039bb03c3c923a.json",
  "parameterValues" : [ ]
}